/**
 * API Error codes enum.
 */

export enum ApiErrorCode {
    TOPIC_NOT_FOUND = "TOPIC_NOT_FOUND",
    TOPIC_ALREADY_PROCESSED = "TOPIC_ALREADY_PROCESSED",
    INVALID_WEIGHTS = "INVALID_WEIGHTS",
    UNAUTHORIZED = "UNAUTHORIZED",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    OPTION_NOT_FOUND = "OPTION_NOT_FOUND",
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION",
}





